version: '3'

services:
  database:
    image: 'postgres'
    restart: 'always'
    environment:
      - POSTGRES_USER=monster
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=university
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data